micronaut:
  application:
    name: delivery-service
  server:
    port: 8083
netty:
  default:
    allocator:
      max-order: 3
#kafka:
#  bootstrap:
#    servers: localhost:9092

app:
  newOrdersTopic: new-orders-topic
  deliveredOrdersTopic: delivered-orders-topic
  cancelledOrdersTopic: cancelled-orders-topic
  errorOrdersTopic: error-orders-topic

